apiVersion: v1
kind: Secret
metadata:
  name: sc-agent-rolesanywhere
  namespace: test-a
  labels:
    app: sc-agent-rolesanywhere
type: Opaque
data:
  certificate.pem: Q2VydGl...Cg==
  private_key.pem: LS0t...WJsZWQu